# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestERRsignin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_eRRsignin(self):
    self.driver.get("https://agro-yakist.com.ua/")
    self.driver.maximize_window()
    self.driver.find_element(By.CSS_SELECTOR, ".pull-right:nth-child(2) .hidden-sm").click()
    self.driver.find_element(By.LINK_TEXT, "Вхід").click()
    self.driver.find_element(By.ID, "input-password").click()
    self.driver.find_element(By.ID, "input-email").click()
    self.driver.find_element(By.ID, "input-email").send_keys("0507odv2005@gmail.com")
    self.driver.find_element(By.ID, "input-password").click()
    self.driver.find_element(By.ID, "input-password").send_keys("123456wrong")
    self.driver.find_element(By.LINK_TEXT, "Вхід").click()
    message = self.driver.find_element(By.CSS_SELECTOR, ".alert").text
    assert " ".join(message.split())  == "× E-Mail і/чи пароль не співпадають."
  
