# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAddingtocart():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_addingtocart(self):
    self.driver.get("https://agro-yakist.com.ua/")
    self.driver.set_window_size(0, 0)
    self.driver.find_element(By.CSS_SELECTOR, ".content-wrapper").click()
    self.driver.find_element(By.LINK_TEXT, "Петрушка Гіганте Італія 20 г, розфасоване насіння (Україна)").click()
    self.driver.find_element(By.ID, "button-cart").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".modal-heading").text == "Кошик"
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".product-table-body-row > .name")
    assert len(elements) > 0
    assert self.driver.find_element(By.LINK_TEXT, "Петрушка Гіганте Італія 20 г, розфасоване насіння (Україна)").text == "Петрушка Гіганте Італія 20 г, розфасоване насіння (Україна)"
  
