# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCHECKaddingtocart():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    # wait for the webpage to be fully rendered
    self.wait = WebDriverWait(self.driver, 10)  # 10 sec
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_cHECKaddingtocart(self):
    self.driver.get("https://agro-yakist.com.ua/")
    self.driver.maximize_window()

    cart_button = self.wait.until(
        expected_conditions.element_to_be_clickable(
            (By.CSS_SELECTOR, "#cart > .btn")
        )
    ) #waiting for the cart button to be clickable
    cart_button.click()

    modal_heading= self.wait.until(
        expected_conditions.visibility_of_element_located(
                (By.CSS_SELECTOR, ".modal-heading")
            )
    )
    assert modal_heading.text == "Кошик"

    self.wait.until(
        expected_conditions.presence_of_element_located(
            (By.CSS_SELECTOR, ".product-table-body-row:nth-child(1) > .remove")
        )
    )
    elements = self.driver.find_elements(
        By.CSS_SELECTOR, ".product-table-body-row:nth-child(1) > .remove"
    )
    assert len(elements) > 0
  
