# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait

# import custom utility class


class TestAddingtocart():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.driver.maximize_window()
    # wait for the webpage to be fully rendered
    self.wait = WebDriverWait(self.driver, 10) #10 sec
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()

  def test_addingtocart(self):
    self.driver.get("https://agro-yakist.com.ua/")

    WebHelpers.wait_for_page_ready(self.driver)

    recommended = self.wait.until(
        expected_conditions.presence_of_element_located(
            (By.XPATH, "//*[contains(text(), 'Рекомендовані товари')]")
        )
    )

    WebHelpers.scroll_into_view(self.driver, recommended, block="start")

    WebHelpers.hide_overlay_if_present(
        self.driver,
        self.wait,
        By.ID,
        "menuMask"
    )

    # wait for at least one button visible & clickable (not just DOM render)
    first_button = self.wait.until(
        expected_conditions.element_to_be_clickable(
            (By.CSS_SELECTOR, ".btn-addtocart")
        )
    )

    WebHelpers.scroll_into_view(self.driver, first_button, block="center")
    WebHelpers.js_click(self.driver, first_button)

    modal_heading = self.wait.until(
        expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".modal-heading"))
    )
    assert modal_heading.text == "Кошик"

    self.wait.until(
        expected_conditions.presence_of_element_located(
            (By.CSS_SELECTOR, ".product-table-body-row > .name")
        )
    )

    elements = self.driver.find_elements(
        By.CSS_SELECTOR, ".product-table-body-row > .name"
    )
    assert len(elements) > 0