# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestKeywordsearch():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_keywordsearch(self):
    self.driver.get("https://agro-yakist.com.ua/")
    self.driver.set_window_size(0, 0)
    self.driver.find_element(By.ID, "inputs").click()
    self.driver.find_element(By.ID, "inputs").send_keys("кавун")
    self.driver.find_element(By.ID, "inputs").send_keys(Keys.ENTER)
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".product-layout:nth-child(1) > .product-thumb")
    assert len(elements) > 0
    self.driver.find_element(By.LINK_TEXT, "Кавун Чарльстон Грей / Charleston Gray 20 насінин (GSN-Semences)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".specification tr:nth-child(4) > td:nth-child(2)").text == "Кавуни"
  
