# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSignin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_signin(self):
    self.driver.get("https://agro-yakist.com.ua/")
    self.driver.set_window_size(0, 0)
    self.driver.find_element(By.CSS_SELECTOR, ".pull-right:nth-child(2) > .btn-group > .btn").click()
    self.driver.find_element(By.LINK_TEXT, "Вхід").click()
    self.driver.find_element(By.ID, "input-email").click()
    self.driver.find_element(By.ID, "input-email").send_keys("0507odv2005@gmail.com")
    self.driver.find_element(By.ID, "input-password").click()
    self.driver.find_element(By.ID, "input-password").send_keys("1111")
    self.driver.find_element(By.LINK_TEXT, "Вхід").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "h1").text == "Андрей Овчаренко"
  
