# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRETURNchangelanguage():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_rETURNchangelanguage(self):
    self.driver.get("https://agro-yakist.com.ua/")
    self.driver.set_window_size(0, 0)
    self.driver.find_element(By.CSS_SELECTOR, "#langmark .btn").click()
    self.driver.find_element(By.LINK_TEXT, "Русский").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(1)").text == "Бесплатная доставка «Новой почтой» и «Укрпочтой» до отделения при заказе от 4000 грн при условии полной предоплаты (вес посылки — до 30 кг)"
    self.driver.find_element(By.CSS_SELECTOR, "#langmark .btn").click()
    assert self.driver.find_element(By.LINK_TEXT, "Українська").text == "Українська"
    elements = self.driver.find_elements(By.CSS_SELECTOR, "#langmark .btn")
    assert len(elements) > 0
    self.driver.find_element(By.LINK_TEXT, "Українська").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(1)").text == "Безкоштовна доставка «Новою поштою» та «Укрпоштою» до відділення при замовленні від 4000 грн за умови повної передплати (вага посилки — до 30 кг)"
  
